name: ticket_printing
description: A new Flutter project for ticket printing.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Dependency Injection
  get_it: ^7.6.7
  
  # Database
  drift: ^2.14.0
  sqlite3: ^2.1.0
  sqlite3_flutter_libs: ^0.5.18 # Needed for mobile
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # Storage
  shared_preferences: ^2.2.2
  
  # PDF & Printing
  pdf: ^3.10.8
  printing: ^5.11.1
  
  # UI & Utilities
  gap: ^3.0.0
  intl: ^0.20.2
  google_fonts: ^6.1.0
  equatable: ^2.0.5
  uuid: ^4.2.1
  file_picker: ^10.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.11.1
  drift_dev: ^2.31.0

flutter_launcher_icons:
  android: "ic"
  ios: false
  image_path: "assets/icon/app_icon_small.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon_small.png"
  remove_alpha_ios: true
  
  # Code Generation
  build_runner: ^2.4.8
  drift_dev: ^2.14.0

flutter:
  uses-material-design: true
